disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- line_length
- identifier_name
# Find all the available rules by running:
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
